### ISSUE TITLE
Allow user default fonts

### ISSUE THREAD

**Issue by mustaqimM** [ltGuillaume/WikiMuch#1]
Hey there, thanks for this really awesome project! (It makes wikipedia much more bearable).

I personally use it without the font modifications since it makes the appearance more uniform across sites like this

![Screenshot_2019-09-23 Barry (TV series) - Wikipedia](https://user-images.githubusercontent.com/24436622/65424504-3eb3a080-ddfb-11e9-82a2-1d572c013a83.png)

**Comment by ltguillaume** [comment]
Hi, thanks for the kinds words. That does look great!

I might wanna make both dark mode and font changes optional with two switches. Your colors seem spot-on. Perhaps you could make a fork of this project and include your changes, so I can include a dark theme, too 😃

**Comment by mustaqimM** [comment]
Hi, sorry for the late reply, I didn't get a notification. The dark colours come from the Dark Reader extension. My edits are to do with the font, here's my edit:
https://gist.github.com/mustaqimM/71cca49eb4df64ab4da123d956f1f7c1

**Comment by ltguillaume** [comment]
@mustaqimM Please have a look at the new version. It removes all the Roboto shite and allows you to set your own fonts via the userscript variables `mainFont`, `textFont` and `monoFont`.

It also allows you to toggle the sidebar with `B` and toggle dark mode with `F9`.
