### ISSUE TITLE
myLangs list reset after update

### ISSUE THREAD

**Issue by mo-han** [ltGuillaume/WikiMuch#2]
Everytime updated to new version, the whole script codes gets flashed, then I need to re-config that myLangs list.

Is there anyway to avoid this inconvenience?

**Comment by ltguillaume** [comment]
Hi,

WikiMuch makes use of GreaseMonkey values, so you shouldn't set them in the script itself, but via the userscript's values in your (GreaseMonkey/TamperMonkey/ViolentMonkey) extension. For example, in ViolentMonkey you can set them via the tab `Values` when editing the userscript.

Then you can add a value called `myLangs` and set it to, for example, `[en, simple, de]`.

The same thing goes for the 3 font values.

**Comment by mo-han** [comment]
You are right, but it took me for a while to make it working, because WikiMuch in TamperMonkey doesn't have the "storage" tab by default. However, after I pressed F9 and B to try the new features (not on purpose), the "storage" tab came out and already had some data set in it. So I add 'myLangs' into it and everything seems fine now.

**Comment by ltguillaume** [comment]
That's good to know. In that case, I'll make sure that the next version always saves those values if they don't exist yet.

E: Done.
