### ISSUE TITLE
Sidebar overlaps content

### ISSUE THREAD

**Issue by toddwc** [ltGuillaume/WikiMuch#4]
I really like this look, so thank you. 

My problem, though, when I use this, is that the sidebar overlaps the content. Is this designed to be used with a specific Wikipedia built-in style?

Also, the sidebar, at the very top, overlaps Wikipedia text and controls.

Thanks.

**Comment by ltguillaume** [comment]
Could you show me some screenshots and show me the URLs of the articles shown on them?

**Comment by toddwc** [comment]
A couple screenshots.

It's at https://en.wikipedia.org/wiki/Comparison_of_on-demand_music_streaming_services


![Screenshot 2021-01-12 at 17 07 45](https://user-images.githubusercontent.com/167818/104380666-597ebc80-54f9-11eb-801a-748c205b7da2.png)

![Screenshot 2021-01-12 at 17 08 03](https://user-images.githubusercontent.com/167818/104380665-58e62600-54f9-11eb-9606-8d6a156c6385.png)

**Comment by ltguillaume** [comment]
I can't reproduce that at all.

1. Please try the latest commit I just pushed, it may help
2. Which browser do you use on what platform/OS?
3. Which add-on do you use to apply userscripts?

**Comment by toddwc** [comment]
Nevermind. I moved on.

**Comment by ltguillaume** [comment]
That's your prerogative, of course. Too bad, I'd have liked to help you out.
